---
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: capa-mp-0
  namespace: mn1a
  labels:
    cluster.x-k8s.io/cluster-name: mn1a
spec:
  clusterName: mn1a
  replicas: 2
  template:
    metadata: {}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfig
          name: capa-mp-0
          namespace: mn1a
      clusterName: mn1a
      infrastructureRef:
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachinePool
        name: capa-mp-0
        namespace: mn1a
      version: v1.18.3
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfig 
metadata:
  name: capa-mp-0
  namespace: mn1a
  labels:
    cluster.x-k8s.io/cluster-name: mn1a
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: aws
        cni-bin-dir: /opt/cni/bin
        cni-conf-dir: /etc/cni/net.d
        image-gc-high-threshold: "50"
        image-gc-low-threshold: "45"
        minimum-container-ttl-duration: 1m
        network-plugin: cni
        node-ip: '{{ ds.meta_data.local_ipv4 }}'
      name: '{{ ds.meta_data.hostname }}'
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachinePool
metadata:
  name: capa-mp-0
  namespace: mn1a
  labels:
    cluster.x-k8s.io/cluster-name: mn1a
spec:
  minSize: 2
  maxSize: 10
  availabilityZones: 
    - us-east-1
  mixedInstancesPolicy:
    instancesDistribution:
      onDemandAllocationStrategy: 70%
      spotAllocationStrategy: 30%
  subnets:
  - subnet-001ce8521fc0ff8ee
  - subnet-0e6fd2254a3edd445
  - subnet-084643f2d519641d2
  - subnet-0095f8e9af90436c3
  - subnet-00d991131ece58510
  - subnet-0fad75c691e4aaec6
  - subnet-0cc7f9817f4f11f2b
  - subnet-05f032cfe56e1d282
  - subnet-0e047440f7463e561
  - subnet-04b81b95a8f080794
  - subnet-0dc8c381c86f393ed
  - subnet-05ec57fb262b50d82
  awsLaunchTemplate:
    ami: 
      id: "ami-067a5ac98cd18ae7d"
    instanceType: "t2.medium"
    sshKeyName: "confab_development"
    iamInstanceProfile: "iam_profile-node-testing"
    blockDeviceMappings:
    - deviceName: "/dev/xvda"
      ebs:
        encrypted: false
        volumeSize: 80
        volumeType: gp2
    networkInterfaces:
    - groups:
      - sg-0e5dfcb2de6ae495b
      - sg-02f5ddf1ac23d18d6
  # extra tags for internal billing i think
  additionalTags:
    department: product
    environment: testing
    owning_team: CONFAB
    product: shared_container_fabric
